TARGET = game.exe

SRCS = src/main.c \
       src/crop.c \
       src/growth.c \
       src/inventory.c \
       src/water.c

CC = gcc
CFLAGS = -Iinclude
LDFLAGS = -lraylib -lopengl32 -lgdi32 -lwinmm

all: clean build run

build:
	$(CC) $(SRCS) -o $(TARGET) $(CFLAGS) $(LDFLAGS)

run:
	./$(TARGET)

clean:
	rm -f $(TARGET)
